source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod "Masonry"
pod 'RDVTabBarController'
pod 'ProtocolBuffers', '1.9.7'
pod 'FMDB'
pod 'AVOSCloud'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh'
pod 'CLImageEditor'
pod 'HMSegmentedControl'
pod 'THLabel', '~> 1.4.6'
pod 'DLRadioButton'
pod 'SDWebImage', '~>3.7'
pod 'ImagePlayerView'
pod 'Vertigo'